name = "WIASJuliaRegistry"
uuid = "b316a774-8fc0-47ae-81a4-53ac7603f492"
repo = "git@github.com:WIAS-BERLIN/WIASJuliaRegistry"
description = "Registry for WIAS Julia packages"

[packages]
c2baa7de-46fc-46aa-8bc7-b446de048749 = { name = "WIASRegistryTest", path = "W/WIASRegistryTest" }
